### ISSUE TITLE
Interface declarations for TypeScript

### ISSUE THREAD

**Issue by some-user123** [ip2location-nodejs/IP2Location#12]
I'd really appreciate [typescript type declarations](https://www.typescriptlang.org/docs/handbook/2/type-declarations.html) as part of this package. This would make it much easier to use it in typescript projects :-)

**Comment by ip2location-nodejs** [comment]
We are unable to do that because it might break existing users' codes.

**Comment by some-user123** [comment]
You could release a new major version where such changes are expected.

You could also publish them as a separate package, e.g. `@types/ip2location-nodejs`.

**Comment by ip2location-nodejs** [comment]
We'll look into your suggestion for future development.

**Comment by ip2location** [comment]
FYI, we've just added the TypeScript type declarations.
