### ISSUE TITLE
No Async Support or Memory Cache

### ISSUE THREAD

**Issue by radiofrequency** [ip2location-nodejs/IP2Location#2]
Never use this script on a production system.  It uses synchronous file io for every ip lookup which is something your not advised to do when using nodejs.

**Comment by chrislim2888** [comment]
thanks for the input. We will review it, but at this moment it will be file i/o access.

**Comment by milonas115** [comment]
@radiofrequency The developers clearly have never worked in Node. Opening an closing a file pointer on EVERY SINGLE read is ridiculous. @chrislim2888 We are not talking about loading the entire database into memory, but as a minimum just open ONE file pointer to the file and read from it. Literally involves modifying 5 lines of code. I won't even bother making a push request as this entire library is just embarrassing.
