### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by GeekStocks** [ip2location-nodejs/IP2Location#5]
While implementing, I had a hard time because there is not a lot of documentation here. The points of difficulty were:

1. IP2Location publishes an IPv4 and an IPv6 BIN file, but apparently you don't need both files to do both types. The naming of the files makes one think that if you have an IPv6 address you need to use IPv6 BIN, and vice versa for IPv4. But in fact the test.js in this projects 'src' folder shows both IPv4 and IPv6 formats being resolved by the IPv6 BIN, and I have confirmed with my own data that indeed the IPv6 BIN does both. So it is confusing why there are 2 files, and it would be good to explain the proper usage of the 2 BIN files. 

2. The library gives an error code 'IPv6 not supported' and it would be good to have an explanation of the error messages that this library gives off.

The BIN files are **fast** and this project has a lot going for it. Just needs documentation now.

**Comment by ip2location-nodejs** [comment]
We have added more information regarding the points you had mentioned. Hopefully things are clearer now.

**Comment by GeekStocks** [comment]
Much clearer - thanks!
