### ISSUE TITLE
Why is npm a dependency in package.json?

### ISSUE THREAD

**Issue by yuvalt** [ip2location-nodejs/IP2Location#7]
Seems requiring that as a dependency pulls many other dependencies.  Maybe you meant to put:

`{ "engines" : { "npm" : "~5.8" } }`

**Comment by ip2location-nodejs** [comment]
It was added by npm automatically when we upgraded the npm version. Are you experiencing issues using this package?

**Comment by ip2location-nodejs** [comment]
We have removed the npm from the dependencies.
