### ISSUE TITLE
Can`t resolve fs in 'ip2location-nodejs\src' with angular 6 Node 8

### ISSUE THREAD

**Issue by godomainz** [ip2location-nodejs/IP2Location#8]
It seems "fs" package is removed from npm.
So this package no longer works.
You should modify the code to work with alternative solution

**Comment by ip2location-nodejs** [comment]
Our Node.js v8.9.4 is able to install the fs package. Did you see any announcements anywhere on the removal of the fs package?

**Comment by godomainz** [comment]
Please have a look at the message at
https://www.npmjs.com/package/fs

**Comment by ip2location-nodejs** [comment]
Please note that fs is part of the Node.js core and so it is not inside NPM.

https://stackoverflow.com/questions/46441591/do-i-need-to-dicretely-install-fs-module-in-node
